name: Lint Podspec

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install CocoaPods
        run: gem install cocoapods
      - name: Lint Podspec
        env:
          # For info on how to obtain a new token see
          # https://medium.com/swlh/automated-cocoapod-releases-with-github-actions-8526dd4535c7
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk me
          pod spec lint FireworkVideo.podspec --verbose
